{{- range .Values.keyVault.secrets }}
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ .name | lower }}-sync
  namespace: {{ $.Values.namespace }}
spec:
  vault:
    name: {{ $.Values.keyVault.name }}
    object:
      name: {{ .name }}
      type: secret
  output:
    secret:
      name: {{ .k8sSecretName }}
      dataKey: {{ .dataKey }}
{{- end }}

