apiVersion: v1
kind: Service
metadata:
  name: usernode-js-service
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.port.userprofile }}
      targetPort: {{ .Values.port.userprofile }}
      protocol: TCP
  selector:
    app: userprofile
